parent=base
import=common/keycloak

styles=css/qstyles.mtrainersssxx1.css

kcHtmlClass=login-pf
kcLoginClass=login-wrapper
kcFormCardClass=card-pf
kcLabelClass=control-label
kcInputClass=form-control
kc-form-buttons=form-group-center-button
kcInputClassCompleteWidth=form-control-width-100
kcFormGroupClass=form-group
kcFormGroupClassLogin=form-group-center-button
kcFormGroupCenterAlignClass=form-group-center-align
kcFormGroupMarginAlignClass=form-group-margin-align
kcCustomCheckBoxClass=input-control-checkbox
kcCustomButtonClass=input-control-button
kcCustomButtonClassAligning=input-control-button-aligning
kcCustomLinkClass=input-control-link
kcCustomLinkClassAlign=input-control-link-align
kcFormIconClass=infx-lgn-icon-container
kcFormIconUsername=infx-lgn-span-username
kcFormIconPassword=infx-lgn-span-password
kcFormIconClassLoginContainer=infx-lgn-span-login-container
kcFormIconClassLogin=infx-lgn-span-login
kcAlertClass=iasthemealert
scripts=js/ehandlejsevents.js